version: "3"

services: 
    mc:
        image: "itzg/minecraft-server:java8"
        ports: 
            - 25565:25565
            - 25575:25575
        environment: 
            EULA: "TRUE"
            TYPE: "CURSEFORGE"
            CF_SERVER_MOD: "/data/SevTech-Ages_Server_3.1.7.zip"
            OVERRIDE_SERVER_PROPERTIES: "true"
            ENABLE_RCON: "true"
            RCON_PASSWORD: "minecraft"
            ONLINE_MODE: "FALSE"
            TZ: "Europe/Rome"
            MAX_TICK_TIME: "-1"
            ENABLE_AUTOPAUSE: "TRUE"
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes: 
            - ./server-data:/data
